const MAX_CREDIT_CARD_NAME_LENGTH = 80;
const MAX_CREDIT_CARD_USER_LENGTH = 80;
const MAX_FAST_ACCESS_BILL_TEXT_LENGTH = 120;
const MAX_FAST_ACCESS_LINK_LABEL_LENGTH = 80;
const MAX_FAST_ACCESS_LINK_URL_LENGTH = 500;

const CREDIT_CARD_ISSUERS = [
  'citi',
  'amex',
  'discover',
  'boa',
  'chase',
  'capital_one',
  'wells_fargo',
  'other',
];

const FAST_ACCESS_BILL_STATUSES = ['Paid', 'Unpaid'];

module.exports = {
  CREDIT_CARD_ISSUERS,
  FAST_ACCESS_BILL_STATUSES,
  MAX_CREDIT_CARD_NAME_LENGTH,
  MAX_FAST_ACCESS_BILL_TEXT_LENGTH,
  MAX_FAST_ACCESS_LINK_LABEL_LENGTH,
  MAX_FAST_ACCESS_LINK_URL_LENGTH,
  MAX_CREDIT_CARD_USER_LENGTH,
};
