const TRANSACTION_KINDS = ['income', 'expense'];
const MAX_TRANSACTION_CATEGORY_LENGTH = 100;
const MAX_TRANSACTION_ACCOUNT_LENGTH = 100;
const MAX_TRANSACTION_NOTE_LENGTH = 500;

module.exports = {
  TRANSACTION_KINDS,
  MAX_TRANSACTION_CATEGORY_LENGTH,
  MAX_TRANSACTION_ACCOUNT_LENGTH,
  MAX_TRANSACTION_NOTE_LENGTH,
};
