const PORT = process.env.PORT || 3000;
const DATABASE_URL = process.env.DATABASE_URL;
const REDIS_URL = process.env.REDIS_URL;
const CACHE_TTL_SECONDS = Number.parseInt(process.env.CACHE_TTL_SECONDS || '30', 10);
const DASHBOARD_CACHE_TTL_SECONDS = Number.parseInt(
  process.env.DASHBOARD_CACHE_TTL_SECONDS || String(CACHE_TTL_SECONDS || 30),
  10
);
const TASK_PAGE_CACHE_TTL_SECONDS = Number.parseInt(
  process.env.TASK_PAGE_CACHE_TTL_SECONDS || String(CACHE_TTL_SECONDS || 30),
  10
);
const NOTE_PAGE_CACHE_TTL_SECONDS = Number.parseInt(
  process.env.NOTE_PAGE_CACHE_TTL_SECONDS || String(CACHE_TTL_SECONDS || 30),
  10
);
const WEATHER_PAGE_CACHE_TTL_SECONDS = Number.parseInt(
  process.env.WEATHER_PAGE_CACHE_TTL_SECONDS || String(CACHE_TTL_SECONDS || 30),
  10
);
const TASK_ALERT_TO = process.env.TASK_ALERT_TO;

if (!DATABASE_URL || DATABASE_URL.includes('[YOUR-PASSWORD]')) {
  throw new Error('DATABASE_URL must be set to your Supabase Postgres connection string.');
}

module.exports = {
  CACHE_TTL_SECONDS: Number.isFinite(CACHE_TTL_SECONDS) && CACHE_TTL_SECONDS > 0 ? CACHE_TTL_SECONDS : 30,
  DASHBOARD_CACHE_TTL_SECONDS: Number.isFinite(DASHBOARD_CACHE_TTL_SECONDS) && DASHBOARD_CACHE_TTL_SECONDS > 0
    ? DASHBOARD_CACHE_TTL_SECONDS
    : 30,
  DATABASE_URL,
  NOTE_PAGE_CACHE_TTL_SECONDS: Number.isFinite(NOTE_PAGE_CACHE_TTL_SECONDS) && NOTE_PAGE_CACHE_TTL_SECONDS > 0
    ? NOTE_PAGE_CACHE_TTL_SECONDS
    : 30,
  PORT,
  REDIS_URL,
  TASK_PAGE_CACHE_TTL_SECONDS: Number.isFinite(TASK_PAGE_CACHE_TTL_SECONDS) && TASK_PAGE_CACHE_TTL_SECONDS > 0
    ? TASK_PAGE_CACHE_TTL_SECONDS
    : 30,
  TASK_ALERT_TO,
  WEATHER_PAGE_CACHE_TTL_SECONDS: Number.isFinite(WEATHER_PAGE_CACHE_TTL_SECONDS) && WEATHER_PAGE_CACHE_TTL_SECONDS > 0
    ? WEATHER_PAGE_CACHE_TTL_SECONDS
    : 30,
};
